name: Node CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest , macos-latest]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing dependencies
      run: |
        npm i
    - name: Building UI
      run: |
        npm run script:build
        npm run build:webpack
    - name: Running unit tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm run test:mocha
    - name : Building
      run: |
        npm run build:electron
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name : Building for RPM
      if: ${{ runner.os == 'Linux' }}
      run: |
        npm run build:electron:rpm
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}